const OSHI_HISTORY_KEY="oshikatsu_page_histories_v1";
function ohLoadAll(){try{return JSON.parse(localStorage.getItem(OSHI_HISTORY_KEY)||"[]")}catch(e){return[]}}
function ohSaveAll(list){localStorage.setItem(OSHI_HISTORY_KEY,JSON.stringify(list.slice(0,200)))}
function ohPageType(){const p=location.pathname;if(p.includes("fund"))return"推し活資金診断";if(p.includes("transport")||p.includes("遠征"))return"遠征プランナー";if(p.includes("yearly")||p.includes("年間"))return"目標シミュレーター";if(p.includes("saving")||p.includes("節約"))return"娯楽費捻出診断";if(p.includes("kakeibo"))return"推し活家計簿";return document.title||"診断ページ"}
function ohCollectInputs(){const data={};document.querySelectorAll("input,select,textarea").forEach((el,i)=>{const key=el.id||el.name||("field_"+i);data[key]=el.type==="checkbox"?el.checked:el.value});return data}
function ohApplyInputs(data){Object.entries(data||{}).forEach(([key,value])=>{const el=document.getElementById(key)||document.querySelector(`[name="${key}"]`);if(!el)return;if(el.type==="checkbox")el.checked=!!value;else el.value=value})}
function ohGuessTotal(){for(const s of ["#fundResult strong","#savingResult strong","#transportResult strong","#yearlyResult strong","#kakeiboResult strong",".result-main strong"]){const el=document.querySelector(s);if(el&&el.textContent.trim())return el.textContent.trim()}return"未計算"}
function ohSaveCurrent(){const list=ohLoadAll();const page=ohPageType();const title=prompt("保存名を入力してください",page+" "+new Date().toLocaleDateString("ja-JP"));if(title===null)return;const item={id:Date.now(),page,title:title.trim()||page,total:ohGuessTotal(),inputs:ohCollectInputs(),createdAt:new Date().toLocaleString("ja-JP")};item.searchText=[item.page,item.title,item.total,item.createdAt,JSON.stringify(item.inputs)].join(" ").toLowerCase();list.unshift(item);ohSaveAll(list);ohRenderHistory();alert("保存しました")}
function ohDelete(id){if(!confirm("削除しますか？"))return;ohSaveAll(ohLoadAll().filter(x=>x.id!==id));ohRenderHistory()}
function ohLoad(id){const item=ohLoadAll().find(x=>x.id===id);if(!item)return;ohApplyInputs(item.inputs);alert("入力内容を読み込みました。診断ボタンを押すと再計算できます。")}
function ohCopy(id){const item=ohLoadAll().find(x=>x.id===id);if(!item)return;navigator.clipboard.writeText(`${item.title}\n${item.page}\n結果：${item.total}\n保存日：${item.createdAt}`).then(()=>alert("コピーしました"))}
function ohEsc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function ohRenderHistory(){const area=document.getElementById("oshiHistoryList");if(!area)return;const q=(document.getElementById("oshiHistorySearch")?.value||"").toLowerCase().trim();const current=document.getElementById("oshiHistoryCurrentOnly")?.checked;const page=ohPageType();let list=ohLoadAll();if(current)list=list.filter(x=>x.page===page);if(q)list=list.filter(x=>(x.searchText||"").includes(q));if(!list.length){area.innerHTML='<p class="oshi-history-empty">保存履歴はありません。</p>';return}area.innerHTML=list.map(x=>`<div class="oshi-history-item"><div class="oshi-history-main"><strong>${ohEsc(x.title)}</strong><span>${ohEsc(x.page)} / ${ohEsc(x.createdAt)}</span><b>${ohEsc(x.total)}</b></div><div class="oshi-history-actions"><button type="button" onclick="ohLoad(${x.id})">読み込み</button><button type="button" onclick="ohCopy(${x.id})">コピー</button><button type="button" class="danger" onclick="ohDelete(${x.id})">削除</button></div></div>`).join("")}
function ohInitHistory(){const mount=document.getElementById("oshiHistoryMount");if(!mount)return;mount.innerHTML=`<section class="oshi-history-box"><div class="oshi-history-head"><div><h2>保存履歴</h2><p>入力内容や診断結果をこのブラウザに保存できます。</p></div><button type="button" class="oshi-save-btn" onclick="ohSaveCurrent()">現在の内容を保存</button></div><div class="oshi-history-tools"><input type="text" id="oshiHistorySearch" placeholder="キーワードで検索"><label><input type="checkbox" id="oshiHistoryCurrentOnly" checked> このページの履歴だけ表示</label></div><div id="oshiHistoryList" class="oshi-history-list"></div></section>`;document.getElementById("oshiHistorySearch")?.addEventListener("input",ohRenderHistory);document.getElementById("oshiHistoryCurrentOnly")?.addEventListener("change",ohRenderHistory);ohRenderHistory()}
document.addEventListener("DOMContentLoaded",ohInitHistory);
